apiVersion: apps/v1
kind: Deployment
metadata:
    name: courses-microservice
    namespace: online-learning-platform-namespace
spec:
    replicas: 3
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 1
            maxSurge: 1
    selector:
        matchLabels:
            app: courses-microservice
    template:
        metadata:
            labels:
                app: courses-microservice
        spec:
            containers:
                - name: courses-microservice
                  image: only1adwy/courses:latest
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 8080
                      - containerPort: 9990
                  resources:
                      limits:
                          memory: "2048Mi"
                          cpu: "1000m"
                      requests:
                          memory: "512Mi"
                          cpu: "250m"
