#For deployment
FROM golang:1.22.3-bullseye as builder

WORKDIR /src
COPY . .
RUN go mod download
RUN CGO_ENABLED=1 GOOS=linux go build -o /app -a -ldflags '-linkmode external -extldflags "-static"' .

FROM scratch

COPY --from=builder /app /app

EXPOSE 3000

ENTRYPOINT ["/app"]


# For development
# FROM golang:1.22.3

# WORKDIR /src

# COPY ./app .

# CMD [ "/src/app" ]
